<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312181457 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31246235A76ED395 ON game_sessions (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_game_session_token ON game_sessions (token)');
        $this->addSql('ALTER TABLE game_sessions ADD CONSTRAINT FK_31246235A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_sessions DROP CONSTRAINT FK_31246235A76ED395');
        $this->addSql('DROP TABLE game_sessions');
    }
}
